apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  labels:
    name: api
spec:
  selector:
    matchLabels:
      name: api
  replicas: 1
  template:
    metadata:
      labels:
        app: api
        name: api
    spec:
      containers:
        - name: api
          image: iampetrovpavel/english-api
          # imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 3000
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: PORT
              value: "3000"
            # - name: SERVICES
            #   value: services/api.service.js
            - name: TRANSPORTER
              value: http://nats:4222
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: api-service
  labels:
    name: api-service
spec:
  # type: NodePort
  # sessionAffinity: ClientIP
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 443
      name: https
      targetPort: 3000
      protocol: TCP
  selector:
    app: api