apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: english-client
  template:
    metadata:
      labels:
        app: english-client
    spec:
      containers:
        - name: english-client
          image: iampetrovpavel/english-client
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: english-client-srv
spec:
  selector:
    app: english-client
  ports:
    - name: english-client
      protocol: TCP
      port: 80
      targetPort: 80