apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "english-ip"
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/enable-cors: "true"
spec:
  rules:
    - host: test.ru
      http:
        paths:
          - path: /api/*
            pathType: Prefix
            backend:
              service: 
                name: english-api-srv
                port: 
                  number: 80
          - path: /*
            pathType: Prefix
            backend:
              service: 
                name: english-client-srv
                port: 
                  number: 3000