apiVersion: apps/v1
kind: Deployment
metadata:
  name: words-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: words
  template:
    metadata:
      labels:
        app: words
    spec:
      containers:
        - name: words
          image: iampetrovpavel/english-words
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            # - name: SERVICES
            #   value: services/clients.service.js
            - name: TRANSPORTER
              value: http://nats:4222
            - name: POSTGRE_URI
              value: 'postgresql://words-postgre:5432/words'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: JWT_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"