apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-words-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: english-words
  template:
    metadata:
      labels:
        app: english-words
    spec:
      containers:
        - name: english-words
          image: iampetrovpavel/english-words
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: TRANSPORTER
              value: http://english-nats:4222
            - name: MONGO_URI
              value: 'mongodb://words-mongo:27017'
            - name: MONGO_DB
              value: 'words'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: english-secrets
                  key: JWT_KEY
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"