apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-api
  labels:
    name: english-api
spec:
  selector:
    matchLabels:
      name: english-api
  replicas: 1
  template:
    metadata:
      labels:
        app: english-api
        name: english-api
    spec:
      containers:
        - name: english-api
          image: iampetrovpavel/english-api
          ports:
            - name: english-api
              containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            - name: PORT
              value: "3000"
            - name: TRANSPORTER
              value: http://english-nats:4222
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: english-secrets
                  key: JWT_KEY
            - name: COOKIE_KEY
              valueFrom:
                secretKeyRef:
                  name: english-secrets
                  key: COOKIE_KEY
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: english-api-srv
  labels:
    name: english-api-srv
spec:
  ports:
    - port: 80
      name: http
      targetPort: 3000
      protocol: TCP
    - port: 443
      name: https
      targetPort: 3000
      protocol: TCP
  selector:
    app: english-api