apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-nats
  labels:
    name: english-nats
spec:
  selector:
    matchLabels:
      name: english-nats
  replicas: 1
  template:
    metadata:
      labels:
        name: english-nats
    spec:
      containers:
        - image: nats
          name: english-nats
          ports:
            - containerPort: 4222
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always
---

apiVersion: v1
kind: Service
metadata:
  name: english-nats
  labels:
    name: english-nats
spec:
  ports:
    - port: 4222
      targetPort: 4222
  selector:
    name: english-nats