apiVersion: apps/v1
kind: Deployment
metadata:
  name: english-users-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: english-users
  template:
    metadata:
      labels:
        app: english-users
    spec:
      containers:
        - name: english-users
          image: iampetrovpavel/english-users
          env:
            - name: LOGGER
              value: "true"
            - name: LOGLEVEL
              value: info
            # - name: SERVICES
            #   value: services/clients.service.js
            - name: TRANSPORTER
              value: http://english-nats:4222
            - name: MONGO_URI
              value: 'mongodb://users-mongo:27017'
            - name: MONGO_DB
              value: 'users'
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: english-secrets
                  key: JWT_KEY
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"