POST https://test.ru/api/translates/find
Content-Type: application/json

###
POST https://test.ru/api/users/learned
Content-Type: application/json

{
    "id": "624c111d4325cb0034034566" 
}

###
POST https://test.ru/api/users/words
Content-Type: application/json

{
    "page": 1,
    "pageSize": 5
}

###
POST https://test.ru/api/users/random
Content-Type: application/json