POST https://test.ru/api/users/find

###
POST https://test.ru/api/users/me

###
POST https://test.ru/api/users/wellcome
Content-Type: application/json

{
    "email": "admin@admin.ru",
    "password": "1212"
}

###
POST https://test.ru/api/users/login
Content-Type: application/json

{
    "email": "test1@test.ru",
    "password": "1212"
}

###
POST https://test.ru/api/users/reg
Content-Type: application/json

{
    "name": "test",
    "email": "test222@test.ru",
    "password": "1212"
}

###
POST https://test.ru/api/users/create
Content-Type: application/json

{
    "name": "user",
    "email": "user@user.ru",
    "password": "1212"
}

###
POST https://test.ru/api/users/remove
Content-Type: application/json

{
    "id": "6235fa46b45e83004a84771a"
}

###
POST https://test.ru/users/validate
Content-Type: application/json

{
    "email": "admin@admin.ru",
    "password": "1212"
}
