POST https://test.ru/api/words/find
Content-Type: application/json

###
POST https://test.ru/api/words/list
Content-Type: application/json

{
    "page": 1,
}

###
POST https://test.ru/api/words/random

###
POST https://test.ru/api/words/create
Content-Type: application/json

{
    "text": "!!!!!!!!!",
    "trans": ["проверка12, проверка123"]
}

###
POST https://test.ru/api/words/remove
Content-Type: application/json

{
    "id": "6238a43bcf8024001e8924a1"
}