POST http://test.ru/api/words/find
Content-Type: application/json

{
    "sort":"createdAt"
}

###
POST https://test.ru/api/words/list
Content-Type: application/json

{
    "page": 1,
    "sort": "createdAt"
}

###
POST https://test.ru/api/words/random

###
POST https://test.ru/api/users/login
Content-Type: application/json

{
    "email": "test@test.ru",
    "password": "1212"
}

###
POST https://test.ru/api/words/create
Content-Type: application/json

{
    "word": "test1221",
    "translate": "проверка4511"
}