name: deploy-api

on:
  push:
    branches:
      - master
    paths:
      - 'api/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd api && docker build -f Dockerfile.prod -t iampetrovpavel/english-api:latest .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}          
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      - run: docker push iampetrovpavel/english-api
